
/**
 * API Endpoint: admin/images
 * Generated by TxMedia API Generator
 * 
 * Authentication: simple
 * Database: Direct PostgreSQL
 */

interface RequestBody {
  // Define your request body interface here
}

interface ResponseData {
  // Define your response data interface here
}
import { NextApiRequest, NextApiResponse } from 'next'
import { Client } from 'pg'
import fs from 'fs'
import path from 'path'


    const client = new Client({
      connectionString: process.env.DATABASE_URL
    })
    
    await client.connect()

export const config = {
  api: {
    bodyParser: {
      sizeLimit: '50mb'
    }
  }
}

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'POST') {
    return res.status(405).json({ message: 'Method not allowed' })
  }

  try {
    // Gallery access should be verified through session storage or password verification
    // This endpoint assumes proper authentication has been established

    // Handle multipart form data upload
    const { files, gallerySlug } = req.body // Implement proper file parsing

    if (!files || files.length === 0) {
      return res.status(400).json({ message: 'No files provided' })
    }

    if (!gallerySlug) {
      return res.status(400).json({ message: 'Gallery slug is required' })
    }

    // Find gallery
    
    const result = await client.query(`
      SELECT * FROM "Gallery"
      WHERE "slug" = $1
    `, [$1])
    
    const gallery = result.rows[0]

    if (!gallery) {
      return res.status(404).json({ message: 'Gallery not found' })
    }

    const uploadedImages = []
    const galleryDir = path.join(process.cwd(), 'public', 'galleries', gallerySlug)
    const thumbnailDir = path.join(galleryDir, 'thumbnails')

    // Ensure directories exist
    if (!fs.existsSync(galleryDir)) {
      fs.mkdirSync(galleryDir, { recursive: true })
    }
    if (!fs.existsSync(thumbnailDir)) {
      fs.mkdirSync(thumbnailDir, { recursive: true })
    }

    // Process each file
    for (const file of files) {
      // Implement file processing logic
      const fileName = `${Date.now()}-${file.originalName}`
      const filePath = path.join(galleryDir, fileName)
      
      // Save file logic here
      
      // Create database record
      
      const imageResult = await client.query(`
        INSERT INTO "GalleryImage" (id, "fileName", "originalName", "filePath", "fileSize", "width", "height", "galleryId", "createdAt", "updatedAt")
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW(), NOW())
        RETURNING *
      `, [
        generateId(),
        fileName,
        file.originalName,
        `/galleries/${gallerySlug}/${fileName}`,
        file.size,
        0, // Get from image processing
        0, // Get from image processing
        gallery.id
      ])
      
      const image = imageResult.rows[0]
      
      uploadedImages.push(image)
    }

    res.status(200).json({
      message: 'Images uploaded successfully',
      images: uploadedImages,
      count: uploadedImages.length
    })
    
    await client.end()

  } catch (error) {
    console.error('admin images error:', error)
    if (client) {
      await client.end()
    }
    res.status(500).json({ message: 'Internal server error' })
  }
}


function generateId() {
  return `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`
}

function getClientIP(req: NextApiRequest): string {
  const forwarded = req.headers['x-forwarded-for']
  const ip = forwarded 
    ? (Array.isArray(forwarded) ? forwarded[0] : forwarded.split(',')[0])
    : req.socket.remoteAddress || 'unknown'
  return ip
}